<?php
namespace CreditRecord\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'SFZHGGWYH' => 1,
        'GQTPXSW' => 2,
        'SWMB' => 3,
        'RMYHPXSZXZH' => 4,
        'SQXJ' => 5,
        'SZJRMFY' => 6,
        'SLSJ' => 7,
        'SGAJ' => 8,
        'SCZJ' => 9,
        'SGYHXXHWYH' => 10,
        'SGYZCJDGLWYH' => 11,
        'SJYJ' => 12,
        'SSFJ' => 13,
        'SRLZYHSHBZJ' => 14,
        'SJSJ' => 15,
        'SGHJ' => 16,
        'SRQYXGS' => 17,
        'SSLJ' => 18,
        'SGDGS' => 19,
        'SLYJ' => 20,
        'SJTYSJ' => 21,
        'SLYFZWYH' => 22,
        'SFDCGLJ' => 23,
        'SHJBHJ' => 24,
        'SSWJ' => 25, 
        'SMZJ' => 26,
        'SNYJ' => 27,
        'SWHGDXWCBS' => 28,
        'SGTZYJ' => 29,
        'SWSHJHSYWYH' => 30,
        'SGJSWJ' => 31,
        'SDFSWJ' => 32,
        'STJJ' => 33,
        'SSCHZLJGGLJ' => 34,
        'SAQSCJDGLJ' => 35, 
        'ZGYDPXFGS' => 36,
        'PXHCZPXBZ' => 37,
        'SYJFJ' => 38,
        'SGGZWGLJ' => 39,
        'ZGDXPXFGS' => 40,
        'SCSGLXZZFJ' => 41,
        'ZGLTPXFGS' => 42,
        'SJGBZWYHBGS' => 43,
        'STYJ' => 44,
        'SDAJ' => 45, 
        'SKXJSJ' => 46
    );
}